### ISSUE TITLE
It takes 12 minutes to process one image.

### ISSUE THREAD

**Issue by njuaplusplus** [AAAAAAsuka/Impress#1]
Thanks for the interesting paper and this implementation.

When I run the code, I find the overhead is very high, as it takes about 12 minutes on one NVIDIA RTX A6000 to purify one image. The GPU-Util is 100% so I think it's running on the GPU.

In your paper, it says "Under our experimental setup, the purification of a single image took an average of 141 seconds".

May I know what hardware you used for the evaluation? 

Thanks a lot.

**Comment by njuaplusplus** [comment]
I used the default parameters in https://github.com/AAAAAAsuka/Impress/blob/main/glaze_pur.py#L91-L95

**Comment by AAAAAAsuka** [comment]
Hi,

Thank you for appreciating our paper!

Our experiments were runed on an NVIDIA A100. 
You might want to try uncommenting line 33 in the ```glaze_pur.py``` file, which is
```python
pipe_img2img.enable_xformers_memory_efficient_attention()
```
in our experiments, thats helped in some cases.

**Comment by Manu21JC** [comment]
When using xformer, it also takes about 12 minutes to purify one image on an NVIDIA RTX 3090, is there any other way to speed up?

**Comment by AAAAAAsuka** [comment]
> When using xformer, it also takes about 12 minutes to purify one image on an NVIDIA RTX 3090, is there any other way to speed up?

Hi Jiachen,

Unfortunately, we're not trying any other acceleration methods right now, so I don't know if other acceleration methods will work.

But you can try to reduce the iter of purify, for our experimental test artists, 500 iters sometimes have a good result. our paper's appendix E might help, thank you!

Best,
Bochuan

**Comment by njuaplusplus** [comment]
> When using xformer, it also takes about 12 minutes to purify one image on an NVIDIA RTX 3090, is there any other way to speed up?

It also takes about 12 minutes with xformer on NVIDIA RTX A6000.
