### ISSUE TITLE
The default glaze_alpha is not the same with describe.

### ISSUE THREAD

**Issue by ZeliuFoo** [AAAAAAsuka/Impress#7]
The default glaze_alpha describe here is 30. However, it is actually 50 in the glaze_origin.py. I failed to reproduce the results for this reason. Hope this bug can be fixed.
![image](https://github.com/AAAAAAsuka/Impress/assets/74546597/6a9ee8e1-9027-4503-a52d-b610a17f23ce)
![image](https://github.com/AAAAAAsuka/Impress/assets/74546597/82be1718-2577-4ce3-8cdf-ca71e283e44e)

**Comment by ZeliuFoo** [comment]
I execute the code step by step. Hope this bug can be fixed.

**Comment by AAAAAAsuka** [comment]
thank you! I've fix it :)
