### ISSUE TITLE
How apply Impress on other protect method

### ISSUE THREAD

**Issue by youyuanyi** [AAAAAAsuka/Impress#8]
Hi, I want to ask how to apply your Impress on other protect method,such as Mist,Anti-DreamBooth,SDS.
Which code should I use?

**Comment by AAAAAAsuka** [comment]
Hi,

Thank you for your interest in our research work!

First, you need to obtain images protected by these methods. Then you can refer to the steps in the README from Execute Impress onwards to use impress to remove the protective noise and evaluate the results. You may need to reorganize the images into the format saved in our code, or rewrite the data reading portion of the code. You can also create your own purify script. The core code of our impress is in the ```impress.py``` file.

If you have any other questions, please let me know. Thank you!

Best,
Bochuan
